---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
# Yaml: intended for the GitHUB Actions .yaml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml # pre-commit-hook-yamlfmt only works on valid YAML files
    name: YAML-format-check
    types: [file]
    files: \.(yaml|yml|plan)$
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.1
  hooks:
  - id: yamlfmt
    name: YAML-format
    args:
    - '--mapping=2'
    - '--sequence=2'
    - '--offset=0'
    - '--width=120'
    - '--preserve-quotes'
    types: [file]
    files: \.(yaml|yml|plan)$

# Python: for all the helpers in toolbox/*
- repo: https://github.com/psf/black
  rev: '22.3.0'
  hooks:
  - id: black
    name: Python-format-black
- repo: https://github.com/pycqa/isort
  rev: '5.10.1'
  hooks:
  # Available args: https://pycqa.github.io/isort/docs/configuration/options.html
  - id: isort
    name: Python-format-isort
    args:
    - '--profile=black'
    - '--line-length=88'
- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    name: Python-lint-flake8
    args:
    - '--max-line-length=88'
    - '--extend-ignore=E203' # ignore "whitespace before ':'"
